### ISSUE TITLE
Cycle Prohibited error

### ISSUE THREAD

**Issue by nileshtrivedi** [timbreitkreutz/omniauth-yahoo#11] opened 2015-03-19 08:56 UTC
Trying to login with version 0.0.5 occasionally gives this error on Yahoo's end:

    Cycle Prohibited
    Description: Could not process your request for the document because it would cause an HTTP proxy cycle. Please check the URL and your browser's proxy settings. 

The URL for this error page is: https://api.login.yahoo.com/oauth/v2/request_auth?oauth_token=b4nybbq

Refreshing the page (one or more times) usually resolves this. This error happens about 50% of the time. Other times, the login flow works completely fine.

Does it have anything to do with this gem using Oauth 1.0 flow on an OAuth V2 (as indicated in that URL) end-point?

**Comment by Jollingeorge** [comment] 2015-03-23 06:34
Iam also facing the same problem 
i am using hybrid auth 
sometimes it will work sometimes Cycle Prohibited

**Comment by timbreitkreutz** [comment] 2015-04-06 04:41
Any progress?  I'm not using this gem myself any more, but if you guys send me your sample code I can take a look.

**Comment by Jollingeorge** [comment] 2015-04-06 04:49
The error is happening because when we ask yahoo server for secret token it will send token sometime sometime error and since the error is coming from yahoo server we cannot do anything .

**Comment by nileshtrivedi** [comment] 2015-04-06 05:13
I had to switch to Yahoo's OpenID login because of this issue. With OpenID, I don't get access to user's data but at least my users don't experience this error while logging in. I noticed that Discourse also does the same.

There seems to be something wrong at Yahoo's end.

**Comment by Jollingeorge** [comment] 2015-04-06 05:26
I have already implemented hybridauth in our website all other log-ins  are working gmail, hotmail etc but only yahoo has this problem , can yahoo look in to it and solve it ...

**Comment by timbreitkreutz** [comment] 2015-04-06 06:09
OK thanks.  I guess I'll close this issue for now then :)

**Closed by timbreitkreutz** 2015-04-06 06:09 UTC

**Comment by Jollingeorge** [comment] 2015-04-06 06:16
dude the problem is there if u close it then people will think the problem is solved but it isn't solved login with yahoo with hybridauth will work sometime and sometime it wil not base on yahoo server some mechanism should be there to solve this error so the users don't face this error

**Comment by pravisivadasan** [comment] 2015-05-15 04:57
am facing the same issue, if you guys found any solution please let me know.

**Comment by Jollingeorge** [comment] 2015-05-18 07:24
its yahoo server problem yahoo has to handle the call to its server can anyone inform yahoo about this bug.

**Comment by christ0ph3r** [comment] 2016-06-30 23:31
@Jollingeorge Do you know if yahoo got it sorted?

If anyone figures this out, please share here as well:

https://github.com/hybridauth/hybridauth/issues/651
